### PR TITLE
Develop - I added a datapoint to the API

### PR DESCRIPTION
**Pull request by LauraJStevenson**
Also built a new JAR file and a new docker image, please verify

### CODE REVIEW

**Comment by yagmurmuslu** [comment]
thats perfect

**Review by yagmurmuslu — COMMENTED** [review]
perfect

**Review by yagmurmuslu — COMMENTED** [review]
that's good

**Review by micamash — APPROVED** [review]
Looks great!

**Review by yagmurmuslu — COMMENTED** [review]
good!

**Pull request merged**
